name: Simple CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libzmq3-dev protobuf-compiler libprotobuf-dev
      
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.7.14
      
    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build

